/*****************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one                *
 * or more contributor license agreements.  See the NOTICE file              *
 * distributed with this work for additional information                     *
 * regarding copyright ownership.  The ASF licenses this file                *
 * to you under the Apache License; Version 2.0 (the                         *
 * "License"); you may not use this file except in compliance                *
 * with the License.  You may obtain a copy of the License at                *
 *                                                                           *
 *     http://www.apache.org/licenses/LICENSE-2.0                            *
 *                                                                           *
 * Unless required by applicable law or agreed to in writing;                *
 * software distributed under the License is distributed on an               *
 * "AS IS" BASIS; WITHOUT WARRANTIES OR CONDITIONS OF ANY                    *
 * KIND; either express or implied.  See the License for the                 *
 * specific language governing permissions and limitations                   *
 * under the License.                                                        *
 *                                                                           *
 *                                                                           *
 * This file is part of the BeanShell Java Scripting distribution.           *
 * Documentation and updates may be found at http://www.beanshell.org/       *
 * Patrick Niemeyer (pat@pat.net)                                            *
 * Author of Learning Java; O'Reilly & Associates                            *
 *                                                                           *
 *****************************************************************************/
/* Generated By:JJTree: Do not edit this line. src/bsh\ParserTreeConstants.java */

package tsh.constant;

public interface ParserTreeConstants {

    public final static String T_MethodDeclaration = "MethodDeclaration";
    public final static String T_VariableDeclarator = "VariableDeclarator";
    public final static String T_ArrayInitializer = "ArrayInitializer";
    public final static String T_FormalParameters = "FormalParameters";
    public final static String T_FormalParameter = "FormalParameter";
    public final static String T_ReturnType = "sun.reflect.generics.tree.ReturnType";
    public final static String T_AmbiguousName = "AmbiguousName";
    public final static String T_Assignment = "jdk.nashorn.internal.ir.Assignment";
    public final static String T_TernaryExpression = "TernaryExpression";
    public final static String T_BinaryExpression = "BinaryExpression";
    public final static String T_UnaryExpression = "UnaryExpression";
    public final static String T_CastExpression = "sun.tools.tree.CastExpression";
    public final static String T_PrimaryExpression = "PrimaryExpression";
    public final static String T_MethodInvocation = "MethodInvocation";
    public final static String T_PrimarySuffix = "PrimarySuffix";
    public final static String T_Literal = "sun.tools.jstat.Literal";
    public final static String T_Arguments = "Arguments";
    public final static String T_StarArgument = "StarArgument";
    public final static String T_AllocationExpression = "AllocationExpression";
    public final static String T_ArrayDimensions = "ArrayDimensions";
    public final static String T_Block = "Block";
    public final static String T_SwitchStatement = "sun.tools.tree.SwitchStatement";
    public final static String T_SwitchLabel = "SwitchLabel";
    public final static String T_IfStatement = "sun.tools.tree.IfStatement";
    public final static String T_WhileStatement = "sun.tools.tree.WhileStatement";
    public final static String T_ForStatement = "sun.tools.tree.ForStatement";
    public final static String T_TypedVariableDeclaration = "TypedVariableDeclaration";
    public final static String T_StatementExpressionList = "StatementExpressionList";
    public final static String T_ReturnStatement = "ReturnStatement";
    public final static String T_ExportStatement = "ExportStatement";
    public final static String T_ThrowStatement = "ThrowStatement";
    public final static String T_TryStatement = "TryStatement";
    public final static String T_ListInitializer = "ListInitializer";
    public final static String T_MapInitializer = "MapInitializer";
    public final static String T_LabeledStatement = "LabeledStatement";
    public final static String T_AnnotationMethodDeclaration = "AnnotationMethodDeclaration";


}
